name: "Setup node 24, enables corepack for yarn, and install deps immutably"
description: "Requires 'secrets: inherit' - Sets up Node.js 24, enables corepack for yarn, and installs dependencies immutably"

inputs:
  READER_TOKEN:
    description: 'NPM authentication token (usually secrets.READER_TOKEN)'
    required: true
    type: string
  workspace:
    description: Install dependencien for specific workspace
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - id: corepack
      shell: bash
      run: corepack enable
    - uses: actions/setup-node@v6
      id: setup-node
      with:
        node-version: 24
        cache: yarn
    - id: set-env
      shell: bash
      run: echo "NPM_AUTH_TOKEN=${{ inputs.READER_TOKEN }}" >> $GITHUB_ENV
    - id: yarn-install
      shell: bash
      run: |
        if [ -n "${{ inputs.workspace }}" ]; then
          echo "inputs.workspace is set to '${{ inputs.workspace }}', installing dependencies for that workspace only"
          yarn workspaces focus ${{ inputs.workspace }}
        else
            yarn install --immutable
        fi
