name: "attest-sign"
description: "Generate SBOM, attest and sign docker image"
inputs:
  image:
    description: "Docker image reference"
    required: true
  digest:
    description: "Docker image digest"
    required: true
  team:
    description: "Team"
    required: true
outputs:
  sbom:
    description: "SBOM.json in cyclonedx format"
    value: ${{ steps.attest-sign.outputs.sbom }}
runs:
  using: "composite"
  steps:
    - id: login
      uses: nais/login@v0
      with:
        team: ${{ inputs.team }}
    - name: Generate SBOM, attest and sign image
      id: attest-sign
      uses: nais/attest-sign@v2
      with:
        image_ref: ${{ inputs.image }}@${{ inputs.digest }}
