on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      team:
        required: false
        type: string
        default: tsm

jobs:
  codeql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: github/codeql-action/init@v3
      - uses: github/codeql-action/autobuild@v3
      - uses: github/codeql-action/analyze@v3

  trivy:
    if: github.ref_name == 'main'
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: nais/login@v0
        with:
          team: ${{ inputs.team }}

      - name: Run Trivy
        uses: aquasecurity/trivy-action@0.33.1
        env:
          TRIVY_JAVA_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-java-db"
          TRIVY_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-db"
        with:
          image-ref: ${{ inputs.image }}
          ignore-unfixed: true
          vuln-type: 'os'
          severity: 'CRITICAL,HIGH'
          format: 'sarif'
          output: 'trivy-results.sarif'
          scanners: 'vuln'

      - name: Upload Trivy results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
